### PR TITLE
Add Month and Year in Relative to report base date

### PR DESCRIPTION
**Pull request by Martronic-SA**

### CODE REVIEW

**Comment by sbidoul** [comment]
Note that this one can also be implemented using date ranges and relative date ranges. That's why I kept only week and day which are not easily implementable as date ranges.

Your proposal is interesting in the sense that it's easier for new users to understand.

The downside being it's a few more lines of code to maintain.

**Comment by Martronic-SA** [comment]
Honestly I hadn't understood the date range behavior before looking at the code. I think both can live positively together. Maybe it's missing a little bit of documentation somewhere for the new users.

**Comment by sbidoul** [comment]
@Martronic-SA I just pushed a few test for date range computations: https://github.com/OCA/account-financial-reporting/pull/275/commits/db40bb981a1ed404c944134e21f8cbdb9e871a27

Could you git rebase and add a couple of tests for these year and month types. Then I'll merge it.

**Comment by Martronic-SA** [comment]
Ok, rebased and tests added

**Comment by sbidoul** [comment]
Thanks for the tests! I moved this PR to https://github.com/OCA/mis-builder/pull/19.

**Pull request closed without merging**
