### PR TITLE
[FIX] MIS Builder: backport and various fixes

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR:
- Replaces acsone icon with OCA's. 
- Updates module description
- Adds index.html file. 
- Removes field 'landscape_pdf', as in version 7 there's no capability to export to PDF.
- Corrects a small issue related to timezone. when the user has no timezone assigned, it generated an error message, instead of defaulting to UTC.

### CODE REVIEW

**Comment by lmignon** [comment]
@jbeficent Thank you for your work. Can you cherry pick commits in V8 from a809796c78490b8c147fc9c526bdd8e6f33733d4 to 09d69b97ea1ad4fecea765ee726128266d40461f and  adapt the code do v7 in one Commit? In this way we are sure that we are aligned with V8.

**Comment by JordiBForgeFlow** [comment]
@lmignon I should not include a migration script as in 09d69b9 because the module has not yet ever been added to 7.0, right?

**Comment by JordiBForgeFlow** [comment]
@lmignon I'd like to document better the part on styles, but I have no idea how to use them. There's no example provided either. Can you help me here?

**Comment by laetitia-gangloff** [comment]
Hello @jbeficent 

Default CSS style and CSS style expression ?

If it is the case, in Default CSS style you can set thing like this :

`font-weight: bold ; background-color: rgb(255,255,166)`

And you get the following result :
image

The second is to add a conditionnal style, you can set thing like this :

`'color: red' if nb_commandes > 0 else ''`

And you get the following result :
image

The main difference between Default CSS style and CSS style expression, it is that the first one is set on the line, and the second is set on the cell.

Normaly you can use any CSS style.

**Comment by JordiBForgeFlow** [comment]
Thanks @lmignon I will then add specific instructions in the documentation.

**Comment by lmignon** [comment]
@jbeficent This module is already installed at customers. @laetitia-gangloff can you check if this migration script makes sens for our clients on 7.0?

**Comment by laetitia-gangloff** [comment]
No need of the migration on 7.0. Record have been migrated  at the hand.
But I think it is the same than 8.0.

**Comment by lmignon** [comment]
thank you @laetitia-gangloff. The migration script doesn't seem relevant for our client but IMO but may be for others....

**Comment by JordiBForgeFlow** [comment]
@lmignon Done. I have changed slightly the builder form view, that was disadjusted after removing the PDF landscape field.

Another thing... the results shown in the dashboard and excel hide the decimal places by default. But I can see that in the excel the correct number has been moved. So it is just a visualisation thing. Is there a way to specify the number of digits that should appear? In financial reports it is compulsory to show 2 digits. Thanks!

**Comment by sbidoul** [comment]
@jbeficent for decimal places, there is the rounding column in the KPI definitions.

**Comment by JordiBForgeFlow** [comment]
Thanks @sbidoul!

**Comment by lmignon** [comment]
@jbeficent Thank you! Can you take a look at the errors in travis and fix the remaining issues? https://travis-ci.org/acsone/account-financial-reporting/jobs/84285804

**Comment by JordiBForgeFlow** [comment]
@lmignon I am trying to enter a full Balance Sheet in MIS Builder, but since the Opening/Closing Period is not listed, it is not possible to have the full BS with the balances that were carried over from the previous year. You can only get the balance for one or more periods, excluding the Opening/Closing. 

Is it that MIS Builder is not intended to be used to obtain a Balance Sheet?

**Comment by sbidoul** [comment]
@jbeficent MIS Builider _is_ intended to for BS reporting too.

You must use `bale` to obtain the account balance at the end of the fiscal period. It autodetects opening entries. It is therefore by design that the opening period are not selectable by the user.

`bale` is the same as the deprecated `bals` used in https://github.com/OCA/l10n-belgium/blob/8.0/l10n_be_mis_reports/data/mis_report_bs.xml where you can see examples.

On a related note `bali` is also available to obtain the balance at the beginning of the period (useful to compute cash flow, for instance).

Those two are documented in the legend of the MIS Report Template form, BTW :wink: 

Thanks for your contributions on the backport BTW. Looking forward to reading your documentation.

**Comment by sbidoul** [comment]
Hi @jbeficent could you do the backport part by cherry-picking the 8.0 commits as explained in https://github.com/acsone/account-financial-reporting/pull/7#issuecomment-146102941? This way the alignment with 8.0 is cleaner and authorship of the commits is preserved. Thanks for your work on this backport!

**Comment by JordiBForgeFlow** [comment]
@sbidoul This cherry-picking the 8.0 commits as explained in #7 (comment) is already done in this same PR.

**Comment by sbidoul** [comment]
@jbeficent that's strange, because if you had used `git cherry-pick` we would see the same commits with the same author as in 8.0. In this PR everything is in one commit under your name.

**Comment by JordiBForgeFlow** [comment]
Oh @sbidoul I'm not proficient enough with Git. I did not know that cherry-pick is an actual instruction! What should we do in this case? 

I'm also backporting the changes from https://github.com/OCA/account-financial-reporting/pull/128 to this same PR. Is that ok?

**Comment by sbidoul** [comment]
> What should we do in this case?

Ideally you should reset your branch to the head of acsone:7.0-mis_builder-lmi-2, git cherry-pick the commits from the 8.0 branch and your commits. Then push -f 7.0-mis_builder_eficent_fixes and the PR will be updated.

> I'm also backporting the changes from OCA#128 to this same PR. Is that ok?

Yes, sure

**Comment by JordiBForgeFlow** [comment]
@sbidoul But since version 7.0 uses the old API, is cherry-picking safe? Take into account that for 7.0 additional changes were included, so really the two version are functionally equivalent, but technically different.

**Comment by JordiBForgeFlow** [comment]
@sbidoul For example, porting OCA#128 involved converting the functions to old API. The code in 7 refers to different lines than the code in 8.

**Comment by lmignon** [comment]
@jbeficent If you take a look to the commits on the initial PR https://github.com/acsone/account-financial-reporting/commits/7.0-mis_builder-lmi-2 you'll see that we have preserved all the original ones from 8.0 and make the changes required for the backport in one commit https://github.com/acsone/account-financial-reporting/commit/ea3ab562eb2b67597d671d216d658b308c279136 In this way, it's easy to compare 8.0 with 7.0 and manage the back/formard port of changes.

**Comment by JordiBForgeFlow** [comment]
@sbidoul Is this what you were looking for?

**Comment by sbidoul** [comment]
> @sbidoul Is this what you were looking for?

Yes. Many thanks!

I think you need to move the README.rst back into `__openerp__.py`.
And the last commit for the analytic hooks.

Then I'll merge this and I'll ask @laetitia-gangloff to test it next week and it will be ready to be merged in the official 7.0 branch.

**Comment by JordiBForgeFlow** [comment]
@sbidoul The latest commit for hooks for analytic filtering has not yet been merged into acsone/account-financial-reporting. The commit is only visible in the OCA repo. I cannot use it (to my best knowledge) to cherry-pick it into this PR.

**Comment by sbidoul** [comment]
@jbeficent I juste resynchronized the acsone repo, so it's there now. Note that technically that commit in acsone is exactly the same as in OCA (it's just a clone of the same git repo).

**Comment by JordiBForgeFlow** [comment]
@sbidoul Should I also cherry-pick the commits on mis_builder after 09d69b9, until the last that you just did?

**Comment by sbidoul** [comment]
Hmm. Backporting is indeed a neverending story. In the end it's up to you: we have only one customer using the v7 version and he's happy with what he has now. 

That said, I think there are a couple of bug fixes in the last 3 commits so you may need them.

**Comment by JordiBForgeFlow** [comment]
Well, don't tell ME. I'm looking forward to finish this year and begin an OpenUpgrade project to move this customer to 8.0. Odoo is never easy.... Thanks. I will go ahead then.

**Comment by sbidoul** [comment]
@jbeficent  BTW, I'm considering changing the API for analytic filtering with something like this: https://github.com/acsone/account-financial-reporting/commit/cb17def7be5b662026468b99a02e257b3a899722

This would be more consistent in case you want to put the operational unit selection on the column.

**Comment by JordiBForgeFlow** [comment]
@sbidoul Well, my use case is that given so many projects, one would not want to create a separate MIS Template for each project, but indicate it in the MIS report itself. 

This is how I'm solving the filtering by analytic account now:
image

For operational units I was able to resolve it putting the operating units in the MIS report:

image

**Comment by sbidoul** [comment]
Ok, I'll leave it as is. We can still make it smarter later.

**Comment by JordiBForgeFlow** [comment]
For the last commits I'm getting an error when doing git cherry-pick:
fatal: bad object

[ADD] mis_builder: hooks for analytic filtering f4fbab3  
[UPD] prefix versions with 8.0 af05e07  
[IMP] mis_builder: improve README and add some roadmap ideas 4f60e4c  

Any idea why is this happening?
I did not import this one:
Merge pull request #116 from acsone/8.0-mis_builder-minmax-fix 053541f  
Because it was already considered in the previous 2 commits.

**Comment by JordiBForgeFlow** [comment]
@sbidoul What I'm lacking is the ability to extend the query domain with data that is introduced in the mis.report.instance. The use case would be a user that wants to prepare a report for a specific project. The mis.report (template) contains the generic KPI's for projects. When the user creates a new mis.report.instance, she/he selects the specific analytic account to be reported on, and that would include analytic domain on all the queries defined for that template.

**Comment by JordiBForgeFlow** [comment]
@sbidoul What would be the reason to add a hook to the query domains, at the level of mis.report.query or mis.report? 

Same as hook '_get_additional_move_line_filter' used to extend domains for move lines, in mis.report.instace.period, the hook for queries '_get_additional_filter' should be associated to mis.report.instance.period as well, so that it can fetch data defined in the report, not the template, to complete the query definition.

**Comment by sbidoul** [comment]
@jbeficent That's why I mentioned this other approach https://github.com/acsone/account-financial-reporting/commit/cb17def7be5b662026468b99a02e257b3a899722

So you coud override `_get_additional_query_filter` with something like

```
if query.model_id.name == 'account.analytic.line':
   return [('account_id', '=', self.report_instance_id.analytic_account_id.id)]
```

With `report_instance_id.analytic_account_id` being the new field you add on mis.report.instance.

If that works for you I'll do the PR with https://github.com/acsone/account-financial-reporting/commit/cb17def7be5b662026468b99a02e257b3a899722

**Comment by JordiBForgeFlow** [comment]
@sbidoul I understand. Yes, it would be great. Unfortunately I've had an issue cherry-picking (as explained above), so I'll need to manually backport this PR and the previous ones.

**Comment by JordiBForgeFlow** [comment]
This latest commit now includes a manual cherry picking of v8 commits 4f60e4c af05e07 f4fbab3 and cb17def.

**Comment by JordiBForgeFlow** [comment]
@sbidoul I tested your new PR in v7 and works fine  (included in my last commit)

**Comment by sbidoul** [comment]
Excellent! Thanks @jbeficent. Can you just fix the few pylint errors?

@laetitia-gangloff it would be great if you could do a quick test of this branch on your v7 database.

**Comment by laetitia-gangloff** [comment]
The migration is not compatible with my version (column already exists), but I think it is not a real problem.

For the rest, all seems work as usual.

**Comment by JordiBForgeFlow** [comment]
When this PR is merged I will push a new PR for module "mis_report_analytic_account" that uses the new hooks.

**Pull request merged**
